# This file provides functions to recreate figures in the paper. By default,
# all the necessary data gets loaded instead of just the data needed
# for a particular figure.
# Main figures ----

# Helper function to make a site map
fig_site_map <- function(site_meta) {
  site_sf <- sf::st_as_sf(site_meta, coords=c("tower_lon", "tower_lat"))
  sf::st_crs(site_sf) <- 4326
  
  us_states <- tigris::states(cb=TRUE) %>% tigris::shift_geometry() %>%
    filter(!(STUSPS %in% c("PR", "AS", "GU", "MP", "VI", "HI")))
  
  site_sf_shift <- tigris::shift_geometry(site_sf)
  
  ggplot() +
    geom_sf(data=us_states, fill=NA, color="grey80") +
    ggrepel::geom_label_repel(
      data=site_sf_shift, 
      mapping=aes(label=as.character(n), geometry=geometry),
      stat="sf_coordinates",
      show.legend = FALSE,
      min.segment.length = 0,
      size=3
    ) +
    theme_void()
}

# Labelling local time better
hour_labeller <- function(lab) {
  str_c(
    formatC(lab, width=2, flag="0", format="d"),
    ":00"
  )
}


#' Functions to generate manuscript figures
#'
#' @param sensor_heights Table of Ameriflux sensor heights as returned by [amf_var_heights()]
#' @param site_meta Site metadata table included with package
#' @param tower_color Color used for the tower pattern.
#' @param eb_rad_tcan_summary Table of model validation results as generated by [model_radiometer_comparison()]
#' @param eb_regressions Table of model II regression results as generated by [run_neon_energy_balance()]
#' @param eb_result Table of energy balance model output as generated by [run_neon_energy_balance()]
#' @param grid_eb Table of gs/gbh sensitivity analysis as generated by [gs_gbh_sensitivity()]
#' @param shade_gpp Table of proportion shade GPP in each site as generated by [run_neon_energy_balance()]
#' @param lidar_constants_df, iv_io_data Tables generated by [fit_lidar_constants()]
#' @param max_lai, Maximum leaf area index to use in [fig_s1_lidar_fit()]
#' @param medlyn_data, Medlyn_constants Tables generated by [fit_medlyn_slopes()]
#' @param gs_cutoff, Cutoff to exclude outliers in [fig_s2_medlyn_fit()]
#' @param line_color, Color for the 1:1 line in [fig_s2_medlyn_fit()]
#' @param aq_constants, aq_data Tables generated by [fit_aq_curves()]
#' @param model_radiometer_crosswalk Crosswalk between model layer and radiometer heights generated by [model_radiometer_comparison()]
#' @param wref_g1_regressions Model II regressions from the g1 sensitivity analysis generated by [run_neon_energy_balance()]
#' 
#' @return Corresponding figure from the manuscript.
#' @export
#' 
#'
fig1_sensor_heights <- function(sensor_heights, site_meta, tower_color="grey50") {
  # Filter sensor heights to radiometers and within-canopy microclimate
  sensor_regex <- paste0(c("T_CANOPY_\\d_\\d_\\d", "H2O_\\d_\\d_\\d",
                           "TA_\\d_\\d_\\d", "WS_\\d_\\d_\\d"),
                         collapse="|")
  
  use_sites <- c("ABBY", "DEJU", "JERC", "OSBS", "RMNP", "TALL", "WREF")
  
  sensor_heights_filter <- sensor_heights %>%
    filter(str_detect(Variable, sensor_regex)) %>%
    select(Site_ID, Variable, Height) %>%
    mutate(site_neon = site_meta$site_neon[match(Site_ID, site_meta$site_ameriflux)],
           Height = floor(Height/2)*2,
           vartype = ifelse(str_detect(Variable, "T_CANOPY"), 
                            "Radiometer", 
                            "Microclimate\nTriplet")) %>%
    filter(site_neon %in% use_sites) %>%
    select(-Variable) %>%
    distinct() %>%
    # Drop radiometers below the canopy
    filter(vartype != "Radiometer" | Height >= 2)
  
  # Attach filepath of the tree svgs to metadata table
  site_meta_filepath <- site_meta %>%
    filter(site_neon %in% use_sites) %>%
    mutate(filepath = system.file(
      "graphic_assets", str_c(stringr::str_to_lower(site_ameriflux), ".png"),
      package="LeafTemperature"
    ))
  
  # Make a named vector to match pngs with site
  file_match_vector <- site_meta_filepath$filepath
  names(file_match_vector) <- site_meta_filepath$site_ameriflux
  
  p <- ggplot(site_meta_filepath, aes(x=site_ameriflux, y=tower_height)) +
    # Add the tower top first, this can make it easier to not clip
    # the tower top if the image is resized.
    ggpattern::geom_bar_pattern(
      aes(x="right", y=tower_height),
      fill="black",
      width=0.3,
      stat="identity",
      pattern="image",
      pattern_type = "none",
      pattern_filename=system.file("graphic_assets", "tower_top.png", 
                                   package="LeafTemperature"),
      pattern_scale=-1,
      pattern_gravity="north",
      pattern_yoffset=0.5,
      alpha=0
    ) +
    # Tower tile
    ggpattern::geom_bar_pattern(
      aes(x="right", y=tower_height*0.8),
      stat="identity",
      fill="black",
      pattern="image",
      pattern_type="tile",
      pattern_filename=system.file("graphic_assets", "tower_tile.png",
                                   package="LeafTemperature"),
      pattern_filter="box",
      pattern_scale=-1,
      color=tower_color,
      linewidth=1,
      width=0.2,
      alpha=0
    ) +
    # Now add the trees
    ggpattern::geom_bar_pattern(
      aes(pattern_filename=site_ameriflux, y=canopy_height, x="left"),
      stat="identity",
      pattern="image",
      pattern_gravity="south",
      alpha=0
    ) +
    ggpattern::scale_pattern_filename_manual(values=file_match_vector) +
    # Debug geom to make sure trees match the actual height
    # geom_point(aes(y=canopy_height, x="left"), color="green") +
    geom_point(
      data=sensor_heights_filter,
      mapping=aes(x="right", y=Height, fill=vartype, shape=vartype),
      position=position_dodge(width=0.5),
      col="black",
      size=2.5
    ) +
    scale_shape_manual(values=c(21, 25)) +
    geom_label(aes(label=str_c(site_neon, " (", n, ")")), 
               x=-Inf, y=Inf, vjust=1, hjust=0) +
    facet_wrap(~ site_neon, scales="free_y") +
    # suppress image legend
    guides(pattern_filename="none") +
    # Styling
    labs(x="", y="Height above ground (m)", fill="", shape="") +
    theme(panel.grid.major.x = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_blank(),
          legend.direction="vertical",
          panel.spacing = unit(0.5, "lines"),
          legend.text = element_text(size=rel(1.0)))
  
  # Move the legend to a blank panel
  p <- reposition_legend(p, "center", panel="panel-3-3")

  # Put site map in the other blank panel
  siteMap <- ggplotGrob(fig_site_map(site_meta))
  gtable_add_grob(p, siteMap, t=20, l=11, r=11, b=20, 
                  clip="off", name="map")
}

#' @rdname fig1_sensor_heights
#' @export
fig2_model_one_to_one <- function(eb_rad_tcan_summary) {
  p <- ggplot(eb_rad_tcan_summary, aes(x=TCAN, y=EB_MODEL_Tl)) +
    geom_bin2d() +
    geom_abline(slope=1, intercept=0, color="black", linetype="dashed") +
    scale_fill_viridis_c(limits=c(0, 200), oob=scales::squish) +
    facet_wrap(~ SITE_NEON) +
    coord_equal() +
    labs(x=expression("Radiometer canopy temperature ("*degree*"C)"),
         y=expression("Model leaf temperature ("*degree*"C)"),
         fill="Count") +
    guides(fill = guide_colorbar(
      ticks.colour="black",
      frame.colour="black"
    )) +
    theme(legend.direction = "horizontal")

  reposition_legend(p, "center", panel=c("panel-3-2", "panel-3-3"))
}

#' @rdname fig1_sensor_heights
#' @export
fig3_regression_slopes <- function(eb_regressions) {
  p <- eb_regressions %>%
    mutate(LAYER_L = factor(LAYER_L)) %>%
    ggplot(aes(x=slope_p50, y=LAYER_L)) +
    geom_vline(xintercept=1, color="grey50", linetype="dashed") +
    geom_errorbar(aes(xmin=slope_p025, xmax=slope_p975)) +
    geom_point(aes(fill=prop_Tl_lt_Ta), color="black", size=3, pch=21) +
    geom_label(aes(label=SITE_NEON), x=-Inf, y=Inf,
               hjust="left", vjust="top") +
    scale_fill_viridis_c() +
    scale_y_discrete(limits=rev) +
    scale_x_continuous(limits=c(0.98, 1.20)) +
    facet_grid(SITE_NEON ~ .,
               scales="free_y", space="free") +
    theme(strip.placement="outside",
          strip.background = element_blank(),
          strip.text.y = element_blank(),
          panel.spacing = unit(1, "lines"),
          # Text a little bigger
          legend.text = element_text(size=rel(1.0)),
          # Colorbar a little smaller
          legend.key.height = rel(0.9),
          # No fill
          legend.background = element_rect(fill=NA)
    ) +
    guides(fill = guide_colorbar(
      ticks.colour="black",
      frame.colour="black"
    )) +
    labs(x=expression("T"[L]~"on"~"T"[A]~"regression slope ("*degree*C*"/"*degree*C*")"),
         y=expression("Cumulative LAI (m"^2~"m"^-2*")"),
         fill=expression("Proportion T"[L]~"<"~"T"[A]))
  
  reposition_legend(p, position="right", panel=c("panel-7-1"))
}

#' @rdname fig1_sensor_heights
#' @export
fig4_temp_forcing <- function(eb_result) {
  eb_result_summary <- eb_result %>%
    group_by(SITE_NEON) %>%
    mutate(
      canopy_group = case_when(
        LAYER_L == max(LAYER_L) ~ "Lower",
        LAYER_L == 0 ~ "Upper",
        .default="Middle"
      ),
      canopy_group = factor(canopy_group, levels=c("Lower", "Middle", "Upper"))
    ) %>%
    group_by(SITE_NEON, canopy_group) %>%
    summarize(
      Rn_forcing = mean(EB_MODEL_dT_Rn),
      Rn_sd = sd(EB_MODEL_dT_Rn),
      LE_forcing = -mean(EB_MODEL_dT_LE),
      LE_sd = sd(EB_MODEL_dT_LE),
      net = Rn_forcing + LE_forcing
    )
  
  p <- ggplot(eb_result_summary, aes(y=canopy_group)) +
    geom_bar(aes(x=Rn_forcing, fill="Rn"), stat="identity") +
    geom_bar(aes(x=LE_forcing, fill="LE"), stat="identity") +
    geom_errorbar(aes(x=Rn_forcing, xmin=Rn_forcing-Rn_sd, 
                      xmax=Rn_forcing+Rn_sd),
                  width=0.3) +
    geom_errorbar(aes(x=LE_forcing, xmin=LE_forcing-LE_sd, 
                      xmax=LE_forcing+LE_sd),
                  width=0.3) +
    # geom_point(aes(x=net)) +
    facet_wrap(~ SITE_NEON) +
    scale_fill_manual(
      labels=c("Transpiration", "Net radiation"),
      values=hcl(h=c(195, 15), l=65, c=100)
    ) +
    labs(x="Temperature forcing (K)",
         y="", fill="") +
    theme(legend.text=element_text(size=rel(1.0)))
  
  reposition_legend(p, 'center', panel=c("panel-3-2", "panel-3-3"))
}

#' @rdname fig1_sensor_heights
#' @export
fig5_gs_gbh_sensitivity <- function(grid_eb, eb_result) {
  tot_rad_unique <- unique(grid_eb$tot_rad)
  
  eb_tot_rad <- eb_result %>%
    mutate(
      rad_load = RAD_SW_ABS + RAD_LW_ABS,
      # Map onto the panels in the figure
      tot_rad = tot_rad_unique[sapply(rad_load, function(x) which.min(abs(x - tot_rad_unique)))],
      type="obs"
    )
  
  grid_eb$type <- "grid"
  
  ggplot(grid_eb) +
    metR::geom_contour_fill(mapping=aes(x=gs, y=gbH, z=dT),
                            binwidth=0.1) +
    # geom_contour(mapping=aes(x=gs, y=gbH, z=dT), color="black",
    #              binwidth=0.25) +
    metR::scale_fill_divergent(guide=guide_colorbar(order=1), limits=c(-3, 3)) +
    labs(fill=expression("T"[L]~"-"~"T"[A]~"(K)")) +
    # geom_label_contour(mapping=aes(x=gs, y=gbH, z=dT),
    #                    skip=0, label.placer=label_placer_fraction()) +
    ggnewscale::new_scale_fill() +
    geom_bin2d(data=eb_tot_rad,
               mapping=aes(x=PS_LAYER_GS, y=EB_MODEL_gbH)) +
    scale_fill_viridis_c(guide=guide_colorbar(order=2)) +
    labs(fill="Count") +
    facet_grid(type ~ tot_rad,
               labeller=label_bquote(cols=LW[abs]*"+"*SW[abs]~"="~.(tot_rad)~"W m"^-2)) +
    #xlim(c(gs_min, gs_max)) + ylim(gbH_min, gbH_max) +
    scale_x_continuous(limits=c(0.01, 0.5), expand=c(0, 0)) +
    scale_y_continuous(limits=c(0.25, 5.0), expand=c(0, 0)) +
    labs(x=expression("Stomatal conductance"~"(mol m"^-2~"s"^-1*")"),
         y=expression(atop("Boundary layer conductance", "(mol m"^-2~"s"^-1*")"))) +
    theme(strip.text = element_text(size=rel(0.8)),
          strip.text.y = element_blank())
}


#' @rdname fig1_sensor_heights
#' @export
fig6_shade_gpp <- function(shade_gpp, site_lai) {
  # Shaded GPP calculation
  shade_gpp_sorted <- shade_gpp %>% arrange(desc(prop_gpp_shade)) %>% 
    pull(SITE_NEON)
  
  shade_lai <- shade_gpp %>%
    left_join(site_lai, by="SITE_NEON")
  
  shade_lai %>%
    ggplot(aes(x=LAI, y=prop_gpp_shade)) +
    geom_hline(yintercept=0.552, color="red", linetype="dashed") +
    geom_point() +
    ggrepel::geom_label_repel(aes(label=SITE_NEON)) +
    ylim(0, 0.6) +
    xlim(0, NA) +
    labs(x="Site leaf area index",
         y="Proportion shaded GPP")
}

#' @rdname fig1_sensor_heights
#' @export
fig7_le_rn_flux <- function(eb_result) {
  classif <- eb_result %>%
    mutate(EB_MODEL_dT = EB_MODEL_Tl - LAYER_TA - 273.15) %>%
    filter(abs(EB_MODEL_dT) > 0.25) %>%
    mutate(
      temp_group = factor(ifelse(EB_MODEL_dT < 0, "cold", "hot"), levels=c("hot", "cold"))
    )
  
  label_vec <- c(
    "EB_MODEL_LE"="Latent heat (λE)",
    "EB_MODEL_Rn"="Net radiation (Rn)"
  )
  
  classif %>%
    select(temp_group, EB_MODEL_Rn, EB_MODEL_LE) %>%
    pivot_longer(contains("EB_MODEL")) %>%
    ggplot(aes(x=value)) +
    # Remove black border
    geom_density(aes(fill=temp_group, y=after_stat(scaled)), color=NA) +
    scale_fill_manual(
      values=c("hot"="#fdb863", "cold"="#0571b0"),
      labels=expression(Delta*"T >  0.25 K", Delta*"T < -0.25 K")
    ) +
    facet_wrap(~ name,
               labeller=as_labeller(label_vec),
               scales="free_x") +
    labs(x=expression("Flux magnitude (W m"^-2*")"),
         y="Relative density",
         fill="") +
    theme_bw() +
    theme(axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position="inside",
          legend.justification.inside=c(.95,.9),
          legend.title=element_blank(),
          legend.background = element_rect(fill=NA))+
    guides(fill=guide_legend(override.aes = list(alpha=1)))
}

# Supplemental figures ----

#' @rdname fig1_sensor_heights
#' @export
fig_s1_lidar_fit <- function(lidar_constants_df, iv_io_data, 
                             max_lai=7) {
  clai <- seq(0, max_lai, length.out=20)
  iv_io_extrapolate <- expand.grid(clai, 1:nrow(lidar_constants_df)) %>%
    cbind(lidar_constants_df[.$Var2, ]) %>%
    select(-Var2) %>% rename(clai = Var1) %>%
    mutate(Beam = exp(kb_real * clai),
           Diffuse = exp(kd_real * clai)) %>%
    pivot_longer(c(Beam, Diffuse))
  
  ggplot(iv_io_data, aes(x=cum_lai, y=iv_io_mean)) +
    geom_point(aes(color=proportion_diffuse_bin)) +
    geom_line(data=iv_io_extrapolate, 
              mapping=aes(x=clai, y=value, group=name, linetype=name)) +
    facet_wrap(~ site, scales="free") +
    labs(x="Cumulative LAI", y="Proportion available light",
         color="Proportion diffuse light", linetype="") +
    scale_y_log10()
}
#' @rdname fig1_sensor_heights
#' @export
fig_s2_medlyn_fit <- function(medlyn_data, medlyn_constants, 
                              gs_cutoff=1.5, line_color="grey50") {
  # Some of the P-M Gs values are unreasonable. This are included in fitting
  # but should be excluded from the figure for clarity.
  medlyn_data %>%
    ggplot(aes(x=Gs_mol, y=Gs_mol_predicted)) +
    geom_point(aes(color=VPD)) +
    geom_label(
      data=medlyn_constants,
      mapping=aes(x=0, y=gs_cutoff, label=str_c("g1 = ", 
                                                         format(round(g1, 2), 
                                                                nsmall=2))),
      vjust=1,
      hjust=0
    ) +
    geom_abline(slope=1, intercept=0, color=line_color) +
    coord_equal(xlim=c(0, gs_cutoff), ylim=c(0, gs_cutoff)) +
    scale_color_viridis_c() +
    facet_wrap(~ site_neon) +
    labs(x=expression("Penman-Monteith G"[s]~"(mol m"^-2~"s"^-1*")"),
         y=expression("Model G"[s]~"(mol m"^-2~"s"^-1*")"),
         color="VPD (kPa)")
}
#' @rdname fig1_sensor_heights
#' @export
fig_s3_aq_fit <- function(aq_constants, aq_data) {
  # Show fit on top of raw data
  sw_range <- seq(0, 1250)
  fit_pred <- aq_constants %>%
    mutate(
      A_pred = purrr::pmap(
        list(k_sat, phi_J, theta_J, Rd),
        function(k_sat, phi_J, theta_J, Rd) {
          data.frame(
            A = photosynthesis::marshall_biscoe_1980(sw_range, k_sat, phi_J, theta_J) - Rd,
            Q = sw_range
          )
        }
      )
    ) %>%
    select(site, A_pred) %>% unnest(A_pred)
  
  ggplot(NULL) +
    geom_point(mapping=aes(x=.Qabs, y=.A), data=aq_data, alpha=0.1) +
    geom_line(mapping=aes(x=Q, y=A, color="Fit"), data=fit_pred, lwd=1, show.legend = FALSE) +
    facet_wrap(~ site, scales="free_y") +
    labs(x=expression("Top-of-canopy shortwave (W m"^-2*")"),
         y=expression("Canopy GPP ("*mu*"mol CO"[2]~"m"^-2~s^-1*")"),
         color="")
}
#' @rdname fig1_sensor_heights
#' @export
fig_s4_rad_model_pairings <- function(model_radiometer_crosswalk) {
  # This approach actually duplicates some points on the radiometer side. But
  # you can't see this in the final product so whatever.
  ggplot(model_radiometer_crosswalk) +
    geom_segment(aes(x="Model Layers", xend="Radiometers", y=LAYER_z, yend=Height),
                 linetype="dashed") +
    geom_point(aes(x="Model Layers", y=LAYER_z), fill="orange", pch=22, size=2) +
    # Match color and pch in fig 1
    geom_point(aes(x="Radiometers", y=Height), fill="#00BFC4", pch=25, size=2) +
    facet_wrap(~ SITE_NEON, scales="free_y") +
    labs(x="", y="Height above ground (m)")
}
#' @rdname fig1_sensor_heights
#' @export
fig_s5_g1_sensitivity <- function(wref_g1_regressions) {
  ggplot(wref_g1_regressions, aes(y=factor(LAYER_L))) +
    geom_vline(xintercept=1, color="grey50", linetype="dashed") +
    geom_errorbar(aes(xmin=slope_p025, xmax=slope_p975)) +
    geom_point(aes(x=slope_p50, fill=prop_Tl_lt_Ta), size=2, pch=21) +
    facet_wrap(~ str_c("g1 = ", MEDLYN_g1)) +
    scale_fill_viridis_c() +
    scale_y_discrete(limits=rev) +
    scale_x_continuous(limits=c(0.97, NA)) +
    labs(x=expression("T"[L]~"vs"~"T"[A]~"regression slope ("~degree*C*"/"*degree*C*")"),
         y=expression("Cumulative LAI (m"^2~"m"^-2*")"),
         fill=expression("Proportion T"[L]~"<"~"T"[A])) +
    guides(fill = guide_colorbar(
      ticks.colour="black",
      frame.colour="black"
    ))
}

#' @rdname fig1_sensor_heights
#' @export
fig_s6_omega_density <- function(eb_result) {
  eb_result %>%
    group_by(SITE_NEON) %>%
    mutate(
      canopy_group = case_when(
        LAYER_L == max(LAYER_L) ~ "Lower",
        LAYER_L == 0 ~ "Upper",
        .default="Middle"
      ),
      canopy_group = factor(canopy_group, levels=c("Lower", "Middle", "Upper"))
    ) %>%
    ggplot(aes(x=EB_MODEL_omega, y=SITE_NEON)) +
    #ggridges::geom_density_ridges(scale=1) +
    # Include relative canopy position?
    ggridges::geom_density_ridges(aes(fill=canopy_group), alpha=0.75, scale=0.9) +
    xlim(0, 0.5) +
    scale_y_discrete(limits=rev) +
    labs(y="",
         x=expression("Decoupling coefficient ("*Omega*")"),
         fill="Canopy position")
}

#' @rdname fig1_sensor_heights
#' @export
fig_s7_flux_boxplots <- function(eb_result) {
  eb_result %>%
    select(SITE_NEON, LAYER_L, EB_MODEL_H, EB_MODEL_Rn, EB_MODEL_LE) %>%
    group_by(SITE_NEON) %>%
    rename(
      "H"=EB_MODEL_H,
      "Rn"=EB_MODEL_Rn,
      "λE"=EB_MODEL_LE
    ) %>%
    mutate(
      canopy_group = case_when(
        LAYER_L == max(LAYER_L) ~ "Lower",
        LAYER_L == 0 ~ "Upper",
        .default="Middle"
      ),
      canopy_group = factor(canopy_group, levels=c("Lower", "Middle", "Upper"))
    ) %>%
    pivot_longer(all_of(c("H", "Rn", "λE")), names_to="flux", values_to="value") %>%
    ggplot(aes(x=value, y=canopy_group)) +
    geom_boxplot(aes(fill=flux), position="dodge") +
    geom_vline(xintercept=0, linetype="dashed") +
    facet_wrap(SITE_NEON ~ .) +
    labs(x=expression("Flux magnitude"~"("*W~m^-2*")"), fill="", y="")
}

#' @rdname fig1_sensor_heights
#' @importFrom lmodel2 lmodel2
#' @export
fig_s8_diurnal_beta <- function(eb_result, site_meta) {
  eb_result <- eb_result %>%
    left_join(
      site_meta %>% select(site_ameriflux, utc_offset),
      by=c("SITE_AMF"="site_ameriflux")) %>%
    mutate(TIMESTAMP_LOCAL = TIMESTAMP + hours(utc_offset))
  
  get_lmodel2_slope <- function(x, y) {
    m <- suppressMessages(lmodel2(y ~ x))
    data.frame(
      p025=m$confidence.intervals[3, 4],
      p500=m$regression.results[3, 3],
      p975=m$confidence.intervals[3, 5]
    )
  }
  
  beta_by_hour <- eb_result %>%
    group_by(SITE_NEON) %>%
    mutate(
      layer = case_when(
        LAYER_L == max(LAYER_L) ~ "Lower",
        LAYER_L == 0 ~ "Upper",
        .default="Middle"
      ),
      canopy_group = factor(layer, levels=c("Lower", "Middle", "Upper"))
    ) %>%
    mutate(hour = hour(TIMESTAMP_LOCAL)) %>%
    group_by(SITE_NEON, layer, hour) %>%
    filter(n() > 10) %>%
    do(get_lmodel2_slope(.$LAYER_TA, .$EB_MODEL_Tl-273.15))
  
  p <- ggplot(beta_by_hour, aes(x=hour)) +
    geom_errorbar(aes(ymin=p025, ymax=p975)) +
    geom_point(aes(color=layer, y=p500)) +
    scale_x_continuous(
      labels=hour_labeller,
      breaks=seq(6, 18, by=6)
    ) +
    facet_wrap(~ SITE_NEON) +
    labs(x="Local time",
         y=expression("T"[L]~"on"~"T"[A]~"regression slope ("*degree*C*"/"*degree*C*")"),
         color="") +
    theme(legend.direction = "horizontal")
  
  reposition_legend(p, "center", panel=c("panel-3-2", "panel-3-3"))
}

#' @rdname fig1_sensor_heights
#' @export
fig_s9_cold_leaf_count <- function(eb_result, site_meta) {
  eb_result %>%
    left_join(site_meta %>% select(site_ameriflux, utc_offset),
              by=c("SITE_AMF"="site_ameriflux")) %>%
    mutate(TIMESTAMP_LOCAL = TIMESTAMP + hours(utc_offset)) %>%
    mutate(hour = hour(TIMESTAMP_LOCAL), 
           month=month(TIMESTAMP, label=TRUE, abbr=TRUE),
           iscold=EB_MODEL_Tl-LAYER_TA-273.15 < 0) %>%
    group_by(hour, month) %>%
    summarize(n = sum(iscold)) %>%
    ggplot(aes(x=hour, y=month, fill=n)) +
    geom_tile() +
    scale_x_continuous(labels = hour_labeller, breaks=seq(4, 20, by=4),
                       na.value="gray", expand=c(0, 0)) +
    scale_y_discrete(expand=c(0, 0), limits=rev) +
    scale_fill_viridis_c() +
    labs(x="Local time", y="", fill="Count") +
    theme(panel.background=element_rect(fill="gray", color="gray"),
          panel.grid=element_blank())
}

fig_s10_aet_dt <- function(eb_result, site_meta) {
  eb_result %>%
    left_join(site_meta %>% select(site_ameriflux, utc_offset),
              by=c("SITE_AMF"="site_ameriflux")) %>%
    mutate(TIMESTAMP_LOCAL = TIMESTAMP + hours(utc_offset),
           EB_MODEL_dT = EB_MODEL_Tl - 273.15 - LAYER_TA) %>%
    filter(hour(TIMESTAMP_LOCAL) %in% 10:14) %>%
    mutate(TS_DATE = as.Date(TIMESTAMP_LOCAL)) %>%
    group_by(SITE_NEON, TS_DATE) %>%
    summarize(daily_et_frac = sum(RAD_ACTUAL_ET) / sum(RAD_POT_ET),
              daily_dT = mean(EB_MODEL_dT)) %>%
    filter(daily_et_frac <= 1) %>%
    ggplot(aes(x=daily_et_frac, y=daily_dT)) +
    geom_point() +
    geom_smooth(aes(group=SITE_NEON), method="lm",
                color="red", linetype="dashed") +
    xlim(0, 1) +
    theme_bw() +
    labs(x="Actual ET / Potential ET", y="Leaf-air T difference (K)",
         color="") +
    facet_wrap(~ SITE_NEON)
}

# Spit out all figures ----
# Helper function to prevent overwrites
safe_save <- function(filename, plot, allow_overwrite=FALSE, ...) {
  message("Writing ", filename)
  if (allow_overwrite | !file.exists(filename)) {
    ggsave(filename, plot, ...)
  } else {
    warning(filename, " already exists! Figure not written.")
  }
}

quiet_read <- function(search_dir, filename, ...) {
  read_csv(file.path(search_dir, filename), show_col_types=FALSE, ...)
}

#' Write all manuscript figures to a directory
#'
#' @param site_meta Table of site details, you should use \code{\link{site_meta}} unless you want to use a different set of sites.
#' @param search_dir Directory the function will look in for data tables. This should be the same as `work_dir` in [run_analysis()].
#' @param out_dir Output directory for all the figures.
#' @param overwrite If a figure already exists, should it be overwritten?
#' @param ... Arguments passed to \code{\link[ggplot2]{theme}}. The default is `theme_bw` with a few font size changes.
#'
#' @details
#' This function calls all of the `fig*` functions in sequence. It takes care of reading the right tables to reproduce what you see in the manuscript.
#' 
#' 
#' @return Void, but all the figures get written to `out_dir`.
#' @export
#'
write_all_figures <- function(site_meta, search_dir, out_dir, overwrite=FALSE,
                              ...) {
  message("Writing figures to ", out_dir)
  if (!dir.exists(out_dir))
    dir.create(out_dir)
  # Set ggplot theme ----
  default_theme <- theme_bw()
  
  theme_set(default_theme)
  # Read data ----
  use_sites <- c("ABBY", "DEJU", "JERC", "OSBS", "RMNP", "TALL", "WREF")
  
  # General site metadata
  site_meta <- site_meta %>%
    filter(site_neon %in% use_sites) %>%
    arrange(site_neon) %>%
    mutate(n = row_number())
  
  # Height of ameriflux sensors
  sensor_heights <- amf_var_heights() %>%
    filter(Site_ID %in% site_meta$site_ameriflux) %>%
    mutate(SITE_NEON = site_meta$site_neon[match(Site_ID, site_meta$site_ameriflux)])
  
  # Lidar constants and mean transmission data
  lidar_constants_df <- quiet_read(search_dir, "neon_lidar_constants.csv") %>%
    filter(site %in% use_sites)
  
  iv_io_data <- quiet_read(search_dir, "neon_lidar_transmission_data.csv") %>%
    filter(site %in% use_sites)
  
  # Medlyn model coefficients and fit
  medlyn_data <- quiet_read(search_dir, "cross_site_medlyn_fit_results.csv") %>%
    mutate(site_neon = site_meta$site_neon[match(site, site_meta$site_ameriflux)])
  
  medlyn_constants <- quiet_read(search_dir, "cross_site_medlyn_coefficients.csv") %>%
    mutate(site_neon = site_meta$site_neon[match(site, site_meta$site_ameriflux)]) %>%
    drop_na()
  
  # AQ curve coefficients and fit
  aq_constants <- quiet_read(search_dir, "cross_site_aq_constants.csv") %>%
    filter(site %in% use_sites)
  
  aq_data <- quiet_read(search_dir, "cross_site_aq_data.csv") %>%
    filter(site %in% use_sites)
  
  # Model layer and radiometer pairings
  model_radiometer_crosswalk <- quiet_read(search_dir, file.path("model_run", "model_rad_height_crosswalk.csv")) %>%
    # Attach NEON site code for consistency
    mutate(SITE_NEON = site_meta$site_neon[match(SITE_AMF, site_meta$site_ameriflux)])
  
  # EB model result and lmodel2 regressions
  eb_result <- quiet_read(search_dir, file.path("model_run", "cross_site_eb.csv"))
  eb_regressions <- quiet_read(search_dir, file.path("model_run", "cross_site_tl_ta_slopes.csv"))
  
  # Layer-by-layer model and radiometer comparison
  eb_rad_tcan_summary <- quiet_read(search_dir, file.path("model_run", "cross_site_model_rad_comparison.csv"))
  eb_rad_height_xwalk <- quiet_read(search_dir, file.path("model_run", "model_rad_height_crosswalk.csv"))
  
  # gs/gbh sensitivity analysis
  grid_eb <- quiet_read(search_dir, file.path("model_run", "gs_gbh_sensitivity.csv"))
  
  # Shaded GPP calculation
  shade_gpp <- quiet_read(search_dir, file.path("model_run", "cross_site_shade_gpp.csv"))
  site_lai <- eb_result %>%
    select(SITE_NEON, LAI) %>%
    distinct()
  
  # g1 sensitivity analysis
  wref_g1_sensitivity <- quiet_read(search_dir, file.path("model_run", "wref_eb_g1_sensitivity.csv"))
  wref_g1_regressions <- quiet_read(search_dir, file.path("model_run", "wref_g1_tl_ta_slopes.csv"))
  
  ## Generate all the figs ----
  ### Main text ----
  
  # Since this function returns a gtable, we can't use ggsave to save it.
  
  fname <- file.path(out_dir, "fig1_sensor_heights.png")
  if (!file.exists(fname) | overwrite) {
    gtab <- fig1_sensor_heights(sensor_heights, site_meta)
    message("Writing ", fname)
    png(
      file.path(out_dir, "fig1_sensor_heights.png"),
      width=6.5, height=4, units="in", res=300
    )
    grid::grid.newpage()
    grid::grid.draw(gtab)
    dev.off()
  }
  
  safe_save(file.path(out_dir, "fig2_model_one_to_one.png"),
            fig2_model_one_to_one(eb_rad_tcan_summary),
            allow_overwrite=overwrite,
            width=5, height=4.5)
  
  safe_save(file.path(out_dir, "fig3_regression_slopes.png"),
            fig3_regression_slopes(eb_regressions),
            allow_overwrite=overwrite,
            width=4.5, height=7)
  
  safe_save(file.path(out_dir, "fig4_temp_forcing.png"),
            fig4_temp_forcing(eb_result),
            allow_overwrite=overwrite,
            width=5, height=4.5)
  
  safe_save(file.path(out_dir, "fig5_gs_gbh_sensitivity.png"),
            fig5_gs_gbh_sensitivity(grid_eb, eb_result),
            allow_overwrite=overwrite,
            width=6.5, height=4)
  
  safe_save(file.path(out_dir, "fig6_shade_gpp.png"),
            fig6_shade_gpp(shade_gpp, site_lai),
            allow_overwrite=overwrite,
            width=4.5, height=3)
  
  safe_save(file.path(out_dir, "fig7_le_rn_flux.png"),
            fig7_le_rn_flux(eb_result),
            allow_overwrite=overwrite,
            width=4.5, height=2.5)
  
  ### Supplemental ----
  safe_save(file.path(out_dir, "fig_s1_lidar_fit.png"),
            fig_s1_lidar_fit(lidar_constants_df, iv_io_data),
            allow_overwrite=overwrite,
            width=8, height=6)
  
  safe_save(file.path(out_dir, "fig_s2_medlyn_fit.png"),
            fig_s2_medlyn_fit(medlyn_data, medlyn_constants),
            allow_overwrite=overwrite,
            width=6, height=6)
  
  safe_save(file.path(out_dir, "fig_s3_aq_fit.png"),
            fig_s3_aq_fit(aq_constants, aq_data),
            allow_overwrite=overwrite,
            width=8, height=6)
  
  safe_save(file.path(out_dir, "fig_s4_rad_model_pairings.png"),
            fig_s4_rad_model_pairings(model_radiometer_crosswalk),
            allow_overwrite=overwrite,
            width=8, height=6)
  
  safe_save(file.path(out_dir, "fig_s5_g1_sensitivity.png"),
            fig_s5_g1_sensitivity(wref_g1_regressions),
            allow_overwrite=overwrite,
            width=8, height=6)
  
  safe_save(file.path(out_dir, "fig_s6_omega_density.png"),
            fig_s6_omega_density(eb_result),
            allow_overwrite=overwrite,
            width=4.5, height=3)
  
  safe_save(file.path(out_dir, "fig_s7_flux_boxplots.png"),
            fig_s7_flux_boxplots(eb_result),
            allow_overwrite=overwrite,
            width=7.5, height=6)
  
  safe_save(file.path(out_dir, "fig_s8_diurnal_beta.png"),
            fig_s8_diurnal_beta(eb_result, site_meta),
            allow_overwrite=overwrite,
            width=5, height=4.5)
  
  safe_save(file.path(out_dir, "fig_s9_cold_leaf_count.png"),
            fig_s9_cold_leaf_count(eb_result, site_meta),
            allow_overwrite=overwrite,
            width=6, height=2)
  
  safe_save(file.path(out_dir, "fig_s10_aet_dt.png"),
            fig_s10_aet_dt(eb_result, site_meta),
            allow_overwrite=overwrite,
            width=8, height=6)
}
